library(msigdbr)
library(dplyr)


msig <- msigdbr(species = "Homo sapiens")


selected_sets <- c(
  # Neuro
  "GOBP_CEREBRAL_CORTEX_NEURON_DIFFERENTIATION", 
"GOBP_POSITIVE_REGULATION_OF_NEUROGENESIS",
  "GOBP_CENTRAL_NERVOUS_SYSTEM_NEURON_DIFFERENTIATION",
  "REACTOME_NEURONAL_SYSTEM",
"GOBP_SYNAPTIC_SIGNALING",
"GOBP_NEURON_PROJECTION_DEVELOPMENT",
  
  # Glia
  "GOBP_ASTROCYTE_DIFFERENTIATION",
  "GOBP_OLIGODENDROCYTE_DIFFERENTIATION",
  "GOBP_REGULATION_OF_GLIAL_CELL_DIFFERENTIATION",
"GOBP_MICROGLIA_DIFFERENTIATION",
  
  # Vasculature
  "HALLMARK_ANGIOGENESIS",
  "HALLMARK_HYPOXIA",
  "GOBP_BLOOD_VESSEL_DEVELOPMENT",
  "GOBP_PERICYTE_CELL_DIFFERENTIATION",
"GOBP_ENDOTHELIAL_CELL_DIFFERENTIATION",
"GOBP_VASCULAR_ASSOCIATED_SMOOTH_MUSCLE_CELL_DIFFERENTIATION",
"GOBP_POSITIVE_REGULATION_OF_VASCULATURE_DEVELOPMENT",
"REACTOME_VEGF_SIGNALING",
"REACTOME_CELL_JUNCTION_ORGANIZATION",
"GOBP_NEUROVASCULAR_UNIT",
"GO_CELL_CELL_JUNCTION",
  
  # Immune
  "HALLMARK_INFLAMMATORY_RESPONSE",
  "HALLMARK_TNFA_SIGNALING_VIA_NFKB",
  "HALLMARK_INTERFERON_GAMMA_RESPONSE",
  "GOBP_INNATE_IMMUNE_RESPONSE",
  "GOBP_CYTOKINE_MEDIATED_SIGNALING_PATHWAY",
"HALLMARK_IL6_JAK_STAT3_SIGNALING",
  
  # Metabolism
  "HALLMARK_OXIDATIVE_PHOSPHORYLATION",
  "HALLMARK_GLYCOLYSIS",
  "HALLMARK_APOPTOSIS",
  
  # Proliferation
  "GOBP_POSITIVE_REGULATION_OF_NEURAL_PRECURSOR_CELL_PROLIFERATION",
  "HALLMARK_E2F_TARGETS",
  "HALLMARK_G2M_CHECKPOINT"
)


gene_sets <- msig %>%
  filter(gs_name %in% selected_sets) %>%
  split(x = .$gene_symbol, f = .$gs_name)
